### ISSUE TITLE
add augmentations to trainer in notebook

### ISSUE THREAD

**Issue by pdutoit2011** [farukcankaya/detectron2-multimodal-augmentation-example#1]
I am still looking through your code, but I am correct that the notebooks do not have the multi-modal augmentations added to the trainer yet?

**Comment by farukcankaya** [comment]
Thanks for your interest. It seems that I forgot to push the updated version of the notebooks. You can see an example usage of such augmentations using DefaultTrainer [here](https://github.com/farukcankaya/detectron2-multimodal-augmentation-example/blob/master/train_net.py#L107).

**Comment by pdutoit2011** [comment]
thanks, working really well with Trainer. Thanks for sharing this code!

**Comment by farukcankaya** [comment]
I updated the notebooks if anyone else wonders. They also can be run on Google Colab right away.
